plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'me.modmuss50.mod-publish-plugin' version '0.8.4'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation("com.github.glitchfiend:TerraBlender-fabric:${minecraft_version}-${terrablender_version}")
}

loom {
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}
sourceSets.main.resources.srcDir(project(":common").file("src/generated/resources"))

publishMods {
    file = remapJar.archiveFile
    changelog = file("${project.rootDir}/CHANGELOG.md").text
    type = STABLE
    modLoaders.add("fabric")
    modLoaders.add("quilt")
    displayName.set("Better Biomes ${project.version} for Fabric ${minecraft_version}")
    version = "${project.version}"

    curseforge {
        projectId = "938715"
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        minecraftVersions.add("${minecraft_version}")
        javaVersions.add(JavaVersion.VERSION_21)
    }

    modrinth {
        projectId = "Qs2o8KiI"
        accessToken = System.getenv("MODRINTH_TOKEN")
        minecraftVersions.add("${minecraft_version}")
        embeds("terrablender")
        embeds("fabric-api")
    }
}