# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.0
group=com.example.examplemod
java_version=21

# Mod
mod_name=BetterBiomes
mod_author=CrypticVerse
mod_id=betterbiomes
license=MIT
credits=
description=Adds cool biomes to the game!

# Dependencies
terrablender_version=6.0.0.3

# Common
minecraft_version=1.21.8
minecraft_version_range=[1.21.8, 1.22)
neo_form_version=1.21.8-20250717.133445
parchment_minecraft=1.21.8
parchment_version=2025.07.20

# Fabric
fabric_version=0.129.0+1.21.8
fabric_loader_version=0.16.14

# Forge
forge_version=58.0.1
forge_loader_version_range=[58,)

# NeoForge
neoforge_version=21.8.15
neoforge_loader_version_range=[2,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
