  name: Publish Mod
  on:
    workflow_dispatch

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Resources
          uses: actions/checkout@v3
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 17
            cache: gradle

        - name: Build and Publish
          run: ./gradlew build modrinth curseforge --stacktrace
