  name: Publish Mod
  on:
    workflow_dispatch:

  permissions:
    contents: write

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Resources
          uses: actions/checkout@v4
        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 17

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3

        - name: Build and Publish
          run: ./gradlew clean build modrinth curseforge --stacktrace
          env:
            MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
            CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
            MAVEN_URL: ${{ secrets.MAVEN_URL }}
